[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std", tag = "v1.6.5" }
openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v4.9.0" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
